apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: reegnz/auth-service
    context: auth-service
  - image: reegnz/hello-world
    context: hello-world
deploy:
  kubectl:
    manifests:
    - deployment/auth-service.yaml
    - deployment/ingress.yaml
    - deployment/hello-world.yaml
